# Generated by Django 5.1.7 on 2025-03-19 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('card_checkList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.card')),
            ],
        ),
        migrations.CreateModel(
            name='CheckListCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('to_check', models.BooleanField(default=False)),
                ('check_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('list_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='list_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.list'),
        ),
    ]
