# Generated by Django 5.1.7 on 2025-03-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_card_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
