# Generated by Django 5.1.7 on 2025-05-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_card_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='list_card',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='card_checkList',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='checklistcard',
            old_name='check_list',
            new_name='parent',
        ),
    ]
