# Generated by Django 5.1.7 on 2025-06-23 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_workspace_desk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Чеклист', 'verbose_name_plural': 'Чеклисты'},
        ),
        migrations.AlterModelOptions(
            name='checklistcard',
            options={'verbose_name': 'Элемент чеклиста', 'verbose_name_plural': 'Элементы чеклистов'},
        ),
        migrations.AlterModelOptions(
            name='desk',
            options={'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'Список', 'verbose_name_plural': 'Списки'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'verbose_name': 'Рабочее пространство', 'verbose_name_plural': 'Рабочие пространства'},
        ),
        migrations.RemoveField(
            model_name='list',
            name='list_user',
        ),
        migrations.AddField(
            model_name='list',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.desk'),
        ),
    ]
