# Generated by Django 5.1.7 on 2025-06-23 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_alter_card_options_alter_checklist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.desk'),
            preserve_default=False,
        ),
    ]
